name: Build and test feature pack

on:
  workflow_dispatch:
    branches:
      - '**'
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Restore cached Maven packages
        id: cache-maven-packages
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.m2
            ~/.local/share/containers
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Clean and build
        run: mvn -B -fae clean install

      - name: Cache Maven packages
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.m2
            ~/.local/share/containers
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
